# Site settings
title: Welcome
email: shubhamkasaudhan512@gmail.com
description: Developer's Diary.
baseurl: "/shubham-resume"
twitter_username: kasaudhan512
avatar: "https://pbs.twimg.com/profile_images/743074621281456128/D2G_g6HS.jpg" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Shubham Kasaudhan" # Set default author name
      categories: "resume"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
